export enum QueryKey {
  Session = "session",
  User = "user",
  Llat = "llat",
  Accounts = "accounts",
  AdAccounts = "ad-accounts",
  PageInsights = "page-insights",
  Report = "report",
  MetricReport = "metric-report",
  GoogleAuthUrl = "google-auth-url",
  GoogleIntegration = "google-integration",
  MetaIntegration = "meta-integration",
  GoogleAccounts = "google-accounts",
  DashboardData = "dashboard-data",
  DashboardCompareData = "dashboard-compare-data",
  TopMetaCampaigns = "top-meta-campaigns",
  TopGoogleCampaigns = "top-google-campaigns",
  Credits = "credits",
  ChartData = "chart-data",
  Sources = "sources",
  AdGroups = "ad-groups",
}
