// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SettingsComponentImport = new FileRoute('/settings').createRoute()
const ProductComponentImport = new FileRoute('/product').createRoute()
const PasswordResetComponentImport = new FileRoute(
  '/password-reset',
).createRoute()
const OverviewComponentImport = new FileRoute('/overview').createRoute()
const IntegrationsComponentImport = new FileRoute('/integrations').createRoute()
const GoogleOauthComponentImport = new FileRoute('/google-oauth').createRoute()
const AdvertisingComponentImport = new FileRoute('/advertising').createRoute()
const AboutComponentImport = new FileRoute('/about').createRoute()
const IndexComponentImport = new FileRoute('/').createRoute()

// Create/Update Routes

const SettingsComponentRoute = SettingsComponentImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/settings.component'),
    'component',
  ),
})

const ProductComponentRoute = ProductComponentImport.update({
  path: '/product',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/product.component'),
    'component',
  ),
})

const PasswordResetComponentRoute = PasswordResetComponentImport.update({
  path: '/password-reset',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/password-reset.component'),
    'component',
  ),
})

const OverviewComponentRoute = OverviewComponentImport.update({
  path: '/overview',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/overview.component'),
    'component',
  ),
})

const IntegrationsComponentRoute = IntegrationsComponentImport.update({
  path: '/integrations',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/integrations.component'),
    'component',
  ),
})

const GoogleOauthComponentRoute = GoogleOauthComponentImport.update({
  path: '/google-oauth',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/google-oauth.component'),
    'component',
  ),
})

const AdvertisingComponentRoute = AdvertisingComponentImport.update({
  path: '/advertising',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/advertising.component'),
    'component',
  ),
})

const AboutComponentRoute = AboutComponentImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/about.component'),
    'component',
  ),
})

const IndexComponentRoute = IndexComponentImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutComponentImport
      parentRoute: typeof rootRoute
    }
    '/advertising': {
      preLoaderRoute: typeof AdvertisingComponentImport
      parentRoute: typeof rootRoute
    }
    '/google-oauth': {
      preLoaderRoute: typeof GoogleOauthComponentImport
      parentRoute: typeof rootRoute
    }
    '/integrations': {
      preLoaderRoute: typeof IntegrationsComponentImport
      parentRoute: typeof rootRoute
    }
    '/overview': {
      preLoaderRoute: typeof OverviewComponentImport
      parentRoute: typeof rootRoute
    }
    '/password-reset': {
      preLoaderRoute: typeof PasswordResetComponentImport
      parentRoute: typeof rootRoute
    }
    '/product': {
      preLoaderRoute: typeof ProductComponentImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexComponentRoute,
  AboutComponentRoute,
  AdvertisingComponentRoute,
  GoogleOauthComponentRoute,
  IntegrationsComponentRoute,
  OverviewComponentRoute,
  PasswordResetComponentRoute,
  ProductComponentRoute,
  SettingsComponentRoute,
])
